trigger:

  branches:
    include:
      - main

pool:
  name: 'ts_agent_p'

steps:
  - checkout: none

  - script: |
      target_file_name="taxi_schema.json"
      if [ -d "TaxiService" ]; then
        echo "Removing existing tution directory"
        rm -rf tution
      fi

      echo "Cloning test branch..."
      git clone -b main https://github.com/pramit46/TaxiService.git

      echo "Listing contents..."
      ls -la TaxiService
    displayName: Clone repo and list schema file
  - script: |
      echo "Installing AzCopy..."
      wget https://aka.ms/downloadazcopy-v10-linux -O azcopy.tar.gz
      tar -xf azcopy.tar.gz
      AZCOPY_DIR=$(find . -type d -name "azcopy_linux*")
      sudo cp "$AZCOPY_DIR/azcopy" /usr/local/bin/
      azcopy --version
    displayName: Install AzCopy
  - script: |
        azcopy copy 'TaxiService/taxi_schema.json' 'https://pramit46.dfs.core.windows.net/schema/schema/taxi_schema.json?sp=racwdli&st=2025-07-12T14:42:36Z&se=2025-07-14T22:42:36Z&sv=2024-11-04&sr=c&sig=gKbvH1ptYyCHjnTx0s4rSLmPKoDNdBDv8%2BpPNXHHpuE%3D' --recursive=true